### ISSUE TITLE
MC Requirements?

### ISSUE THREAD

**Issue by shanedewitt** [jonbartels/bootermcgooter#3]
Does this require Mirth Connect 4.4 or later? Just wanted to clarify because I wasn't sure.

**Comment by jonbartels** [comment]
Yes it requires 4.4.0 or newer because it requires the [server startup event](https://github.com/nextgenhealthcare/connect/pull/4861). 

The plugin has to start after the Mirth service is completely live and ready so that the plugin changes the Server Name and Environment Name settings after any built-in Mirth updates are done.

When the plugin was implemented, the only other way I could think of to do this would be to run it as a background task so that it just updates the settings on a timer. I didn't care for that solution. I am receptive to other ideas for how to trigger this event.

Also the long term goal for this plugin is to not exist. This plugin should just be a feature in Mirth Connect https://github.com/jonbartels/bootermcgooter/issues/2
